### ISSUE TITLE
How to use /grieflogger lookup

### ISSUE THREAD

**Issue by robotter112** [DAQEM/GriefLogger#20]
Minecraft : 1.20.1
Fabric: 0.15.6
Mod Version: 1.1.2

Hello,

I'm trying to understand how to use /grieflogger lookup or /grieflogger page, I always get no result. 

In my example, I wanted to see which players have interacted with a lever. That's why I tried this command without success. Is it even possible to display something like this? 

```
/grieflogger lookup action.add_item user.Robotter112
GriefLogger - No results found.
```

**Comment by DAQEM** [comment]
Please specify a Radius. The radius is 0 by default.
