### ISSUE TITLE
Rollback feature

### ISSUE THREAD

**Issue by SageofTurtles** [DAQEM/GriefLogger#52]
Hello! Not sure if perhaps I'm missing something, but is there a rollback feature in this mod? Logs are very helpful, and this appears to be more thorough in logging than CoreProtect and Ledger at a glance. But the biggest advantage of those two add-ons was their ability to easily revert the logged interactions and undo any damage/griefing/theft that had occurred. If I'm understanding correctly, there's no way to do that with Grief logger, is that right? If so, I'd like to suggest it as a feature for a future update.

**Comment by DAQEM** [comment]
GriefLogger does not support rollbacking. Try the Ledger mod.

**Comment by Pankraz01** [comment]
Hi, i have written an addon for this mod. Currently Supporting 1.21.1 on neoforge. But i will make it fully compatible with @DAQEM original Mod on all his releases
